name: Auto-assign workflows

on:
  workflow_call:

jobs:
  assign-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "EU QUERO!!!" comment
        if: contains(github.event.comment.body, 'EU QUERO!!!')
        run: |
          # Extract the commenter's username
          commenter=$(jq -r .comment.user.login $GITHUB_EVENT_PATH)

          # Add the commenter as an assignee to the issue using a Personal Access Token
          echo "Assigning $commenter to the issue..."

          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d "{\"assignees\": [\"$commenter\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees"

  assing-hatters-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Assigna automaticamente o time de hatts no pr
        run: |
          echo ${{inputs.repository}}

          echo ${{inputs.pr-number}}

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"reviewers":[""],"team_reviewers":["hatts"]}'\
            "https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/requested_reviewers"
