name: Auto-assign workflows

on:
  workflow_call:
  workflow_dispatch:

jobs:
  assign-on-issue:
    runs-on: ubuntu-latest
    if: ${{contains(github.event.comment.body, 'EU QUERO!!!')}}
    steps:
      - name: Check for "EU QUERO!!!" comment
        run: |
          # Extract the commenter's username
          commenter=$(jq -r .comment.user.login $GITHUB_EVENT_PATH)

          # Add the commenter as an assignee to the issue using a Personal Access Token
          echo "Assigning $commenter to the issue..."

          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d "{\"assignees\": [\"$commenter\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees"

  assing-hatters-on-pr:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request'}}
    steps:
      - name: Assigna automaticamente o time de hatts no pr
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"reviewers":[""],"team_reviewers":["hatts"]}'\
            "https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/requested_reviewers"

  assing-contributor-on-pr:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request'}}

    steps:
      - name: Check if pr has assignee
        id: check
        run: |
          ASSIGNEES=$(gh pr view ${{ github.event.pull_request.number }} --json assignees --jq '.assignees | length')

          echo "assignees=$ASSIGNEES" >> $GITHUB_ENV        
          shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        if: steps.check.outputs.assignees == 0
        uses: actions/checkout@v4.1.7

      - name: Assigna o criador do pr no proprio pr
        if: steps.check.outputs.assignees == 0
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.actor }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
