name: Playwright Tests
on:
  workflow_call:
    inputs:
      pnpm-version:
        type: string
        default: 8
        required: true
        description: Define pnpm version
      node-version:
        type: string
        default: 20
        required: true
        description: Define a versão do Node

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pnpm And Node
        uses: devhatt/workflows/.github/actions/pnpm-setup@main
        with:
          pnpm-version: ${{inputs.pnpm-version}}
          node-version: ${{inputs.node-version}}

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm dlx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
